CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(15) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(15) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) CHECK(GENDER IN('M','F')),
    AGE NUMBER NOT NULL,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(500),
    HOBBY VARCHAR2(50),
    ENROLL_DATE DATE DEFAULT sysdate    
);

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';

COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원 비밀번호';

COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원 이름';

COMMENT ON COLUMN MEMBER.GENDER IS '성별';

COMMENT ON COLUMN MEMBER.AGE IS '나이';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';

COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';

COMMENT ON COLUMN MEMBER.HOBBY IS '취미';

COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입날짜';

COMMENT ON TABLE MEMBER IS '회원 테이블';


Insert into MEMBER 
(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLL_DATE) values 
('admin','admin','관리자','M',30,'admin@iei.or.kr','01012345678','서울시 강남구 역삼동 테헤란로 
7','기타,독서,운동',to_date('16/03/15','RR/MM/DD'));
Insert into MEMBER 
(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLL_DATE) values 
('user11','pass11','홍길동','M',23,'hong77@kh.org','01077778888','경기도 수원시 팔달구 팔달동 
77','운동,등산,기타',to_date('17/09/21','RR/MM/DD'));
Insert into MEMBER 
(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLL_DATE) values 
('user22','pass22','신사임당','F',48,'shin50@kh.org','01050005555','강원도 강릉시 오죽헌 5','독
서,그림,요리',to_date('17/05/05','RR/MM/DD'));
Insert into MEMBER 
(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLL_DATE) values 
('user77','user77','이순신','M',50,'dltjswnh@naver.com','01021226374','경기도 
시흥시','음악',to_date('17/12/08','RR/MM/DD'));
Insert into MEMBER 
(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLL_DATE) values 
('lsj','lsj','이선주','F',24,'dltjswnh@naver.com','01021226374','경기도 안산시','운동,음악,댄스
',to_date('17/08/25','RR/MM/DD'));
Insert into MEMBER 
(MEMBER_ID,MEMBER_PWD,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,ENROLL_DATE) values 
('seonn','seonn','김공부','F',28,'study11@naver.com','01021226374','경기도 성남시','공부,책읽기
',to_date('17/11/08','RR/MM/DD'));

commit;

SELECT * FROM MEMBER;